{
  fetchurl,
  stdenv,
  lib,
  installShellFiles,
}:

let
  version = "4.19.4";
  assets = {
    x86_64-linux = {
      arch = "amd64";
      hash = "sha256-1h+rITPFRiYeqQzUPS97SliQvE+bVAeTDaGXNibEdCM=";
    };
    aarch64-linux = {
      arch = "arm64";
      hash = "sha256-730f8fJjLNDK25xtTLDCsZBF9FmSYaXQ30plT1F16Yk=";
    };
  };
  asset =
    assets.${stdenv.hostPlatform.system}
      or (throw "zitadel: unsupported platform ${stdenv.hostPlatform.system}");
in
# nixpkgs' zitadel is still 2.x
stdenv.mkDerivation {
  pname = "zitadel";
  inherit version;
  src = fetchurl {
    url = "https://github.com/zitadel/zitadel/releases/download/v${version}/zitadel-linux-${asset.arch}.tar.gz";
    inherit (asset) hash;
  };
  sourceRoot = "zitadel-linux-${asset.arch}";
  installPhase = ''
    install -m755 -D zitadel $out/bin/zitadel
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd zitadel --zsh <($out/bin/zitadel completion zsh)
  '';
  meta = {
    description = "Identity infrastructure (ZITADEL binary, release build)";
    homepage = "https://zitadel.com";
    mainProgram = "zitadel";
    platforms = builtins.attrNames assets;
  };
}
