Host github.com
    Hostname            github.com
    User                git

Host git.karlsen.fr
    Hostname            git.karlsen.fr
    User                git

Host aur.archlinux.org
    Hostname            aur.archlinux.org
    User                aur
