# Private LAN

# 192.169.0.0/24 - Physical machines
Host helios.home.karlsen.fr    # Protectli FW6D / Debian Trixie / Router
Host rax80.home.karlsen.fr     # Netgear Nighthawk RAX80 / WAP
Host xps13.home.karlsen.fr     # Dell XPS 13 9343 / X / Workstation
Host geras.home.karlsen.fr     # Dell XPS 15 7590 / NixOS / Workstation
Host boreas.home.karlsen.fr    # MacBook Pro M1 2021 (j314sap) / Fedora Asahi / Workstation
Host xperia5ii.home.karlsen.fr # Sony Xperia 5 II
Host sk-g990b.home.karlsen.fr  # Samsung Galaxy S21 5G
Host caiman.home.karlsen.fr    # Pixel 9 Pro (SM-G990B/DS)
Host grizzly.home.karlsen.fr   # Pixel 11 Pro
Host hermes.home.karlsen.fr    # Raspberry Pi 4 Model b Rev 1.4 / Debian Trixie / Tailscale node
Host zeus.home.karlsen.fr      # Gigabyte X570 AORUS XTREME) / Windows 11 Pro / Gaming PC
Host atlas.home.karlsen.fr     # Dell Poweredge T420 / Proxmox VE / Hypervisor
Host hera.home.karlsen.fr      # ASUS NUC 15 Pro+ (RNUC15CRSU900002) / Proxmos VE / Hypervisor
# Host chronos.home.karlsen.fr # SuperMicro NixOS NAS / X / Storage server
