# Private LAN - Proxmox VE

## Virtual Machines

# Atlas (Decommissioning)
Host file.atlas.home.karlsen.fr    # Temp fileserver (before moving to chronos - supermicro NAS)
Host torrent.atlas.home.karlsen.fr # Torrent files

## Hera
Host db01.hera.home.karlsen.fr    # Database server 01
Host db02.hera.home.karlsen.fr    # Database server 02
Host file01.hera.home.karlsen.fr  # Fileserver 01
