{
  fetchurl,
  stdenv,
  lib,
  installShellFiles,
}:

let
  version = "0.6.1";
  assets = {
    x86_64-linux = {
      arch = "amd64";
      hash = "sha256-bzmeUny4WIsC19KOrpphxJaA9M1egtmL56XFAByA00E=";
    };
    aarch64-linux = {
      arch = "arm64";
      hash = "sha256-XnCYFTygatVXe09dXNOAsd59e2VQW9iqFgyRgaKxAcU=";
    };
  };
  asset =
    assets.${stdenv.hostPlatform.system}
      or (throw "topf: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "topf";
  inherit version;
  src = fetchurl {
    url = "https://github.com/postfinance/topf/releases/download/v${version}/topf_linux_${asset.arch}.tar.gz";
    inherit (asset) hash;
  };
  sourceRoot = ".";
  installPhase = ''
    install -m755 -D topf $out/bin/topf
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd topf --zsh <($out/bin/topf completion zsh)
  '';
  meta = {
    description = "Talos Orchestrator by PostFinance";
    homepage = "https://github.com/postfinance/topf";
    mainProgram = "topf";
    platforms = builtins.attrNames assets;
  };
}
