{ fetchurl, stdenv, lib, installShellFiles }:

let
  version = "4.3.0";
  assets = {
    x86_64-linux  = { arch = "amd64"; hash = "sha256-hlhKVN73NXBVj2b1ERzFPf7VZoljeuMsEgEgXUlPVPs="; };
    aarch64-linux = { arch = "arm64"; hash = "sha256-McV5TdVcZqUea30uKsehFK6LHeQf8dm6UXSKyXOwagg="; };
  };
  asset = assets.${stdenv.hostPlatform.system}
    or (throw "helm: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "helm";
  inherit version;
  src = fetchurl {
    url = "https://get.helm.sh/helm-v${version}-linux-${asset.arch}.tar.gz";
    inherit (asset) hash;
  };
  installPhase = ''
    install -m755 -D helm $out/bin/helm
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd helm --zsh <($out/bin/helm completion zsh)
  '';
  meta = {
    description = "The Kubernetes package manager";
    homepage = "https://helm.sh";
    platforms = builtins.attrNames assets;
  };
}
