# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Main LUKS container: holds the BTRFS volume with subvolumes for /, /home, and /nix.
  boot.initrd.luks.devices."luks-adfc686d-fd51-471c-afb1-1313b9874d46".device =
    "/dev/disk/by-uuid/adfc686d-fd51-471c-afb1-1313b9874d46";
  fileSystems."/" = {
    device = "/dev/mapper/luks-adfc686d-fd51-471c-afb1-1313b9874d46";
    fsType = "btrfs";
  };
  fileSystems."/home" = {
    device = "/dev/mapper/luks-adfc686d-fd51-471c-afb1-1313b9874d46";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };
  fileSystems."/nix" = {
    device = "/dev/mapper/luks-adfc686d-fd51-471c-afb1-1313b9874d46";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/34C0-24D2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Swap LUKS container: separate encrypted partition for swap.
  boot.initrd.luks.devices."luks-bc43092a-9fe4-4ec7-af2c-6d1221b09d97".device =
    "/dev/disk/by-uuid/bc43092a-9fe4-4ec7-af2c-6d1221b09d97";
  swapDevices = [
    { device = "/dev/mapper/luks-bc43092a-9fe4-4ec7-af2c-6d1221b09d97"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
