{
  fetchurl,
  stdenv,
  lib,
  installShellFiles,
}:

let
  version = "1.53.1";
  assets = {
    x86_64-linux = {
      arch = "x86_64";
      hash = "sha256-Ay/guEmp1qIiSIvIRkRbr+rpk68QJreKgSHQIyHKH9E=";
    };
    aarch64-linux = {
      arch = "arm64";
      hash = "sha256-tug/d5599StGOXx9OfcbHebYkgI5hhpuqg2hTCTgo8Y=";
    };
  };
  asset =
    assets.${stdenv.hostPlatform.system}
      or (throw "stripe-cli: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "stripe-cli";
  inherit version;
  src = fetchurl {
    url = "https://github.com/stripe/stripe-cli/releases/download/v${version}/stripe_${version}_linux_${asset.arch}.tar.gz";
    inherit (asset) hash;
  };
  sourceRoot = ".";
  installPhase = ''
    install -m755 -D stripe $out/bin/stripe
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    (cd "$TMPDIR" && $out/bin/stripe completion --shell zsh > /dev/null)
    installShellCompletion --cmd stripe --zsh "$TMPDIR/stripe-completion.zsh"
  '';
  meta = {
    description = "Stripe CLI tool for interacting with the Stripe API";
    homepage = "https://stripe.com/docs/stripe-cli";
    platforms = builtins.attrNames assets;
  };
}
