{
  fetchurl,
  stdenv,
  lib,
  installShellFiles,
}:

let
  version = "3.5.4";
  assets = {
    x86_64-linux = {
      arch = "amd64";
      hash = "sha256-nNjLn494U1evRBqVRMwcY6K42brUXr6IUDq44xXGSuM=";
    };
    aarch64-linux = {
      arch = "arm64";
      hash = "sha256-/nxzeskS4oH6E9wnsr5mlWNLn+SD1ShG8+fmUGexHBI=";
    };
  };
  asset =
    assets.${stdenv.hostPlatform.system}
      or (throw "argocd: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "argocd";
  inherit version;
  src = fetchurl {
    url = "https://github.com/argoproj/argo-cd/releases/download/v${version}/argocd-linux-${asset.arch}";
    inherit (asset) hash;
  };
  dontUnpack = true;
  installPhase = ''
    install -m755 -D $src $out/bin/argocd
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd argocd --zsh <($out/bin/argocd completion zsh)
  '';
  meta = {
    description = "Declarative GitOps CD for Kubernetes";
    homepage = "https://argo-cd.readthedocs.io";
    platforms = builtins.attrNames assets;
  };
}
