{ fetchurl, stdenv, lib, installShellFiles }:

let
  version = "3.5.3";
  assets = {
    x86_64-linux  = { arch = "amd64"; hash = "sha256-uGD3P1fL3dmTzURvUjbXl8GxrIVUhXsmg9JmnxfnZbQ="; };
    aarch64-linux = { arch = "arm64"; hash = "sha256-uzfl1i34l+oWEPfGR/3Hhleg46ko3CGJP6979mpGRss="; };
  };
  asset = assets.${stdenv.hostPlatform.system}
    or (throw "argocd: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "argocd";
  inherit version;
  src = fetchurl {
    url = "https://github.com/argoproj/argo-cd/releases/download/v${version}/argocd-linux-${asset.arch}";
    inherit (asset) hash;
  };
  dontUnpack = true;
  installPhase = ''
    install -m755 -D $src $out/bin/argocd
    runHook postInstall
  '';
  nativeBuildInputs = [ installShellFiles ];
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  postInstall = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd argocd --zsh <($out/bin/argocd completion zsh)
  '';
  meta = {
    description = "Declarative GitOps CD for Kubernetes";
    homepage = "https://argo-cd.readthedocs.io";
    platforms = builtins.attrNames assets;
  };
}
