{ fetchurl, stdenv, lib, unzip, autoPatchelfHook, installShellFiles }:

let
  version = "2026.9.1";
  assets = {
    x86_64-linux  = { arch = "linux";       hash = "sha256-hCier1nWkfBCQmBREvIbAOjbplrN7bxg3eABooYPIJc="; };
    aarch64-linux = { arch = "linux-arm64"; hash = "sha256-xFHHczeKbx8EHqJlaKiXsoWoZWvuFqFuSRTOnkD7fHk="; };
  };
  asset = assets.${stdenv.hostPlatform.system}
    or (throw "bitwarden-cli: unsupported platform ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "bitwarden-cli";
  inherit version;
  src = fetchurl {
    url = "https://github.com/bitwarden/clients/releases/download/cli-v${version}/bw-${asset.arch}-${version}.zip";
    inherit (asset) hash;
  };
  # Dynamically linked: point it to the C/C++ runtime in the Nix store
  nativeBuildInputs = [ installShellFiles unzip autoPatchelfHook ];
  buildInputs = [ stdenv.cc.cc.lib ];
  # Node.js single executable: the application is embedded in the binary, stripping would break it
  dontStrip = true;
  dontAutoPatchelf = true; # Patched in postInstall instead
  sourceRoot = ".";
  installPhase = ''
    install -m755 -D bw $out/bin/bw
    runHook postInstall
  '';
  # Patch here rather than in the fixup phase: bw has to run below to generate its completion
  postInstall = ''
    autoPatchelf $out
  ''
  # zsh completion, generated by the binary itself (only when it runs on the build machine)
  + lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
    export HOME="$TMPDIR"
    installShellCompletion --cmd bw --zsh <(BITWARDENCLI_APPDATA_DIR="$TMPDIR/bw-appdata" $out/bin/bw completion --shell zsh 2>/dev/null)
  '';
  meta = {
    description = "Bitwarden password manager CLI";
    homepage = "https://bitwarden.com/help/cli";
    mainProgram = "bw";
    platforms = builtins.attrNames assets;
  };
}
